// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Project3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void project3() {
    driver.get("http://localhost:4000/sign_in");
    driver.manage().window().setSize(new Dimension(865, 927));
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.id("add_new_board")).click();
    driver.findElement(By.id("board_name")).sendKeys("Hiii");
    driver.findElement(By.id("board_name")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".inner")).click();
    driver.findElement(By.id("list_name")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".add-new > .inner")).click();
    driver.findElement(By.id("list_name")).sendKeys("jkdmsl");
    driver.findElement(By.id("list_name")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector("li > .add-new")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("li > .add-new"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("cancel")).click();
    driver.findElement(By.linkText("Boards")).click();
    driver.findElement(By.linkText("View all boards")).click();
    driver.findElement(By.cssSelector(".logo")).click();
    driver.findElement(By.cssSelector("span:nth-child(3)")).click();
    driver.findElement(By.cssSelector("#crawler-sign-out > span")).click();
    driver.findElement(By.linkText("Create new account")).click();
    driver.findElement(By.id("user_email")).sendKeys("john@phoenix-trello.com");
    driver.findElement(By.id("user_password")).sendKeys("12345678");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.id("user_first_name")).sendKeys("a");
    driver.findElement(By.id("user_last_name")).click();
    driver.findElement(By.id("user_last_name")).sendKeys("b");
    driver.findElement(By.id("user_password_confirmation")).click();
    driver.findElement(By.id("user_password_confirmation")).sendKeys("s");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.linkText("Sign in")).click();
  }
}
