// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    driver.get("http://localhost:4000/sign_in");
    driver.manage().window().setSize(new Dimension(1157, 947));
    driver.findElement(By.linkText("Create new account")).click();
    driver.findElement(By.id("user_first_name")).click();
    driver.findElement(By.id("user_first_name")).sendKeys("a");
    driver.findElement(By.id("user_last_name")).click();
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.id("user_last_name")).sendKeys("b");
    driver.findElement(By.id("user_email")).click();
    driver.findElement(By.id("user_email")).sendKeys("a");
    driver.findElement(By.id("user_email")).sendKeys("a@g");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.id("user_password")).click();
    driver.findElement(By.id("user_password")).sendKeys("123456");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.id("user_password_confirmation")).click();
    driver.findElement(By.id("user_password_confirmation")).sendKeys("123456");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.id("user_email")).click();
    driver.findElement(By.id("user_email")).sendKeys("a@h");
    driver.findElement(By.id("user_password")).click();
    driver.findElement(By.id("user_password")).sendKeys("12345");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.id("user_password")).click();
    driver.findElement(By.id("user_password_confirmation")).click();
    driver.findElement(By.id("user_password_confirmation")).sendKeys("12345");
    driver.findElement(By.cssSelector("button")).click();
  }
}
